/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bgW8MLC9pAQ
 */
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ThreeSteps } from "./three-steps";
import { Video } from "../ui/video";

export function Lucy() {
  return (
      <div className="lg:w-2/3 relative my-16 p-9 bg-lime-50 mx-auto shadow-2xl rounded-3xl border border-slate-300">
        <div className="flex flex-row mx-auto py-6 px-6">
  
          <div className="relative w-64 h-64">
              <div className="absolute">
                <span className="relative flex h-6 w-6">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-lime-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-6 w-6 bg-lime-500"></span>
                </span>
              </div>
              <Image
                alt="Image"
                className="sm:w-28 sm:h-28 md:w-34 md:h-34 float-left mr-6 mb-6 object-cover rounded-full shadow-xl border-2 border-lime-400"
                src="/lucy2.png"
                width= "100"
                height= "100"
                style={{
                objectFit: "cover",
                }}
              />
          </div>

          <div className="w-128 h-128 float-left">
            <h1 className="animate-fade-up bg-gradient-to-br from-lime-800 to-lime-700 bg-clip-text text-start  font-extrabold tracking-tight text-transparent drop-shadow-sm [text-wrap:balance] text-4xl md:text-3xl pb-4">
              Utopia Research Assistant
            </h1>
            <h1 className="animate-fade-up bg-gradient-to-br from-lime-100 to-slate-100 bg-clip-text text-left  text-transparent drop-shadow-sm [text-wrap:balance] text-3xl md:text-3xl md:leading-[3rem]">
              Your research assistant
            </h1>
          </div>

        </div>

          <div className="min-w-fit min-h-20">
              <ThreeSteps/>
          </div>
        
          <p className="text-2xl italic font-normal text-slate-200 text-center md:ml-8 md:mr-8 md:pl-8 md:pr-8">
                Lucy helps you refine your search, find reliable sources, 
                and interpret the information obtained.<br/>Just chat with her.
          </p> 

          <p className="text-center pt-2">
          <span className="text-blue-200 text-sm">Free for the early birds!</span>
          <Button className="h-13 m-4 bg-slate-200 border border-slate-100 hover:border-fuchsia-200 hover:bg-slate-100 shadow-fuchsia-600/10 hover:shadow-fuchsia-400/20 shadow-xl hover:shadow-xl text-stone-500 hover:text-gray-500" asChild>
              <Link href="https://search.utopia.express/" target="_blank">
                <span className="transition-all mr-3 ml-3 text-slate-500 hover:text-slate-400">Utopia Research Assistant</span>
                <span className="w-10 h-10">
                <Image
                alt="Image"
                className="float-left mr-8 object-cover rounded-full shadow-lg border-slate-100"
                src="/lucy2.png"
                width= "100"
                height= "100"
                style={{
                objectFit: "cover",
                }}
              />
                </span>
              </Link>
          </Button>
          </p>




        
  


      </div>
  )
}


function LinkIcon() {
  return (
<svg className="w-10 h-10 absolute right-4 top-4 opacity-15" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor">
  <path className="" strokeLinecap="round" strokeLinejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
  )
}



