/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bgW8MLC9pAQ
 */
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ThreeSteps } from "./three-steps";
import {
    Carousel,
    CarouselContent,
    CarouselItem,
    CarouselNext,
    CarouselPrevious,
  } from "@/components/ui/carousel";
  import { Posters } from "./posters";
  import { Posters2 } from "./posters2";
  

export function PostersCarousel() {
  return (

    <div className="w-full">
            <Carousel className="cursor-ew-resize">
                <CarouselContent>
                    <CarouselItem>
                        <Posters2/> 
                    </CarouselItem>
                    <CarouselItem>
                        <Posters/> 
                    </CarouselItem>
                </CarouselContent>

                <CarouselPrevious className="left-64 -top-10"/>
                <CarouselNext className="right-64 -top-10"/>

            </Carousel>
    </div>
  )
}


function ArrowIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="float-right w-6 h-6 ">
  <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
  )
}

