/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bgW8MLC9pAQ
 */
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ThreeSteps } from "./three-steps";

export function Purposes() {
  return (

    <div className="mb-9 p-6 lg:p-9 mx-auto border  border-stone-700 rounded-3xl relative bg-gradient-to-br from-stone-900 to-stone-800 shadow-xl shadow-stone-600/80">

        <h1 className="py-6 animate-fade bg-gradient-to-br from-stone-400 to-fuchsia-200 bg-clip-text text-center  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[4rem]">Launch your AI based service</h1>
        <p className="pb-4 text-2xl font-normal text-stone-500 text-center">You bring the idea, I bring the tech. Fully functional, monetizable, rentable systems.</p>
   
        <div className="mt-4 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">

            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:text-stone-800 hover:shadow-xl">
              <h1 className="py-4 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">For interior designers</h1>
              <p className="leading-4 text-xs text-stone-500">Create designs based on a sketch or photo</p>
            </div>

            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:shadow-xl">
              <h1 className="py-4 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">for hairdressers</h1>
              <p className="leading-4 text-xs text-stone-500">Show your customers some cool hairstyles with their own faces</p>
            </div>

            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:shadow-xl">
              <h1 className="py-4 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">for webshop owners</h1>
              <p className="leading-4 text-xs text-stone-500">Create virtual product photos in any enviroment</p>
            </div>

            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:shadow-xl">
              <h1 className="py-4 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">for webshop owners</h1>
              <p className="leading-4 text-xs text-stone-500">Create virtual product photos in any enviroment</p>
            </div>

            
            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:shadow-xl">
              <h1 className="py-4 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">for clothing retailers</h1>
              <p className="leading-4 text-xs text-stone-500">Create a virtual test room for your customers</p>
            </div>

            <div className="transition-all border border-stone-600 p-4 rounded-2xl hover:bg-white hover:shadow-xl">
                <h1 className="py-2 text-xl leading-4 font-bold text-stone-100 hover:text-stone-800">
                    <PlusIcon/>
                </h1>
              <p className="leading-4 text-xs text-stone-500">I'm just a developer, you probably have better ideas.</p>
            </div>

        </div>

        <div className="mt-6 mx-auto text-center">
            <Button variant="secondary" size="lg">
                Contact our Chatbot for details
                <ArrowIcon/>
            </Button>
        </div>


    </div>
  )
}


function PlusIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="text-fuchsia-300 w-9 h-9">
  <path fillRule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25ZM12.75 9a.75.75 0 0 0-1.5 0v2.25H9a.75.75 0 0 0 0 1.5h2.25V15a.75.75 0 0 0 1.5 0v-2.25H15a.75.75 0 0 0 0-1.5h-2.25V9Z" clipRule="evenodd" />
</svg>
  )
}

function ArrowIcon() {
    return (
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 ml-4">
  <path fillRule="evenodd" d="M8.25 3.75H19.5a.75.75 0 0 1 .75.75v11.25a.75.75 0 0 1-1.5 0V6.31L5.03 20.03a.75.75 0 0 1-1.06-1.06L17.69 5.25H8.25a.75.75 0 0 1 0-1.5Z" clipRule="evenodd" />
</svg>
    )
  }





