/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7VFkLwBdWbx
 */
import { Separator } from "@/components/ui/separator";
import Image from "next/image";
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import Typewriter from 'typewriter-effect';
import { ThreeSteps2 } from "./three-steps2";
import Link from "next/link";
import React from "react"; 


export function Research4() {
  return (
    <div>

        <Separator className="w-full h-px bg-stone-300 mt-4 mb-4"/>
            <Link href="https://search.utopia.express" className="" target="_blank">
                <p className="text-xs uppercase tracking-wider text-stone-400/50 hover:text-stone-800">
                    <span className="invisible md:visible">Research & Write</span>
                    <span className="float-right">search.utopia.express <ArrowIcon/></span>
                </p>
            </Link>
        <Separator className="w-full h-px bg-stone-300 mt-4 mb-4"/>

      
        <div className="animate-fade-up animate-delay-300  transition-all w-full grid md:grid-cols-2 lg:grid-cols-3 lg:gap-4">

          <div className="p-4 lg:p-9 lg:col-span-2 sm:mb-8 flex flex-col transition-all rounded-3xl relative"> 

            <h1 className="pb-4 animate-fade bg-gradient-to-br from-stone-700 to-stone-800 bg-clip-text text-left  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[4rem]">
              <span className="">Research & Writer Assistant</span>
            </h1>
            <p className="text-lg text-stone-500 max-w-[480px]">For Content Creators! Cooperation of three autonomous AI agents to make your work more fun & efficient.</p>
            
            <div className="gap-6 grid grid-cols-1 md:grid-cols-3 w-full md:gap-9 pt-6 text-stone-600 text-center">
              <div className="pt-4 text-left transition-all relative mb-6 ">
                <UploadIcon/>
                <p className="pt-4 text-sm leading-5">
                    <span className="font-normal text-stone-500">Understands what you need & helps refine your search</span>
                </p>
              </div>
              <div className="pt-4 text-left transition-all relative mb-6 ">
                <TrainingIcon/>
                <p className="pt-2 text-sm leading-5"> 
                    <span className="font-normal text-stone-500">Collects data in real time & process the result</span>
                </p>
              </div>
              <div className="pt-4 text-left transition-all relative mb-6">
                <GenerateIcon/>
                <p className="pt-2 text-sm leading-5">
                    <span className="font-normal text-stone-500">Chat with an excerpt about the results</span>
                </p>
              </div>
            </div>

          </div>

          <div className="flex flex-col place-content-center transition-all relative"> 
            
            <div className="relative mx-auto shadow-2xl shadow-indigo-900/40 h-96 w-64 mb-6 bg-gradient-to-r from-stone-100 to-stone-50 rounded-2xl p-6 ring-offset-0 ring-8 ring-stone-100/80">
                <div className="relative w-12 h-12">
                    <div className="absolute">
                        <span className="relative flex h-2 w-2">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-stone-700 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-stone-700/10"></span>
                        </span>
                    </div>
                </div>
                <p className="h-28 text-2xl font-extrabold italic text-stone-700">
                    <Typewriter
                    options={{
                    loop: true,
                    delay: 50,
                    }}
                    onInit={(typewriter) => {
                    typewriter
                        .typeString('Collect information about the technological singularity')
                        .pauseFor(1000)
                        .deleteAll()
                        .typeString('Write a blog post based on the information gained')
                        .pauseFor(1000)
                        .deleteAll()
                        .start();
                    }}
                    />
                </p>
                <Link href="https://search.utopia.express" className="hover:text-stone-700" target="_blank">
                    <div className="absolute -left-6 bottom-6">
                        <h2 className="text-5xl font-extrabold">9<span className="text-sm">€/month</span></h2>
                        <Badge variant="green" className="text-xs hover:bg-emerald-400">Try out now!</Badge>   
                    </div>
                </Link>

            </div>   

          </div>       

        </div>

    </div>
  )
}




function UploadIcon() {
  return (
<svg className="w-10 h-10 stroke-stone-400 text-left" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor">
<path strokeLinecap="round" strokeLinejoin="round" d="M7.5 3.75H6A2.25 2.25 0 0 0 3.75 6v1.5M16.5 3.75H18A2.25 2.25 0 0 1 20.25 6v1.5m0 9V18A2.25 2.25 0 0 1 18 20.25h-1.5m-9 0H6A2.25 2.25 0 0 1 3.75 18v-1.5M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
</svg>

  )
}


function GenerateIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-10 h-10 stroke-stone-400 text-left">
<path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
</svg>


  )
}

function TrainingIcon() {
  return (
<svg className=" animate-spin p-1 h-10 w-10 text-white text-left" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
<circle className="stroke-emerald-400" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
<path className=" fill-stone-300" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>
  )
}


function ArrowIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="float-right ml-2 w-4 h-4">
  <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
  )
}


function MergeIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 6 4-4 4 4" />
      <path d="M12 2v10.3a4 4 0 0 1-1.172 2.872L4 22" />
      <path d="m20 22-5-5" />
    </svg>
  )
}



