/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N544DxeuZPU
 */
import { Button } from "@/components/ui/button";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import logo from "@/public/logo.png";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { LetterFx } from "./LetterFx";
import { Video2 } from "@/components/component/video2";


export function Revolution() {
  return (
      <div className="w-full h-full text-gray-800 dark:text-gray-100">
        <Video2/>
      </div>
  )
}


