/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7VFkLwBdWbx
 */
import { Separator } from "@/components/ui/separator";
import Image from "next/image";
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import Typewriter from 'typewriter-effect';
import { ThreeSteps2 } from "./three-steps2";
import Link from "next/link";
import React from "react"; 


export function Voice() {
  return (
    <div>

            <Link href="https://search.utopia.express" className="" target="_blank">
                <p className="text-[10px] uppercase tracking-wider text-stone-400 hover:text-stone-800">
                    <span className="invisible md:visible">Hume.ai</span>
                    <span className="float-right">voice.utopia.express<ArrowIcon/></span>
                </p>
            </Link>
        <Separator className="w-full h-px bg-stone-500/10 mt-4 mb-4"/>

      
        <div className="animate-fade-up animate-delay-300  transition-all w-full grid md:grid-cols-2 lg:grid-cols-3 lg:gap-4">

          <div className="p-4 lg:p-9 lg:col-span-2 sm:mb-8 flex flex-col transition-all rounded-3xl relative"> 
            <h1 className="pb-4 animate-fade bg-gradient-to-br from-stone-700 to-stone-800 bg-clip-text text-left  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[4rem]">
             Empathic Voice Assistants
            </h1>
            <p className="text-lg text-stone-500 max-w-[480px]">AI voice that responds empathically. Built with Hume.ai align technology for human well-being.</p>
            
            <div className="gap-6 grid grid-cols-1 md:grid-cols-3 w-full md:gap-9 pt-6 text-stone-600 text-center">
              <div className="pt-4 text-center transition-all relative mb-6 ">
                <Image 
                src="/lucy2.png" 
                alt="Voice Assistant" 
                width={200} height={200} 
                className="rounded-full w-20 h-20 mx-auto"
                />
                <p className="pt-4 text-sm leading-5">
                    <span className="font-normal text-stone-500">English Tutor</span>
                </p>
              </div>
              <div className="pt-4 text-center transition-all relative mb-6">
                <Image 
                src="/kontotamas2.png" 
                alt="Voice Assistant" 
                width={200} height={200} 
                className="rounded-full w-20 h-20 mx-auto"
                />
                <p className="pt-4 text-sm leading-5"> 
                    <span className="font-normal text-stone-500">Motivational Coach</span>
                </p>
              </div>

            </div>

          </div>

          <div className="flex flex-col place-content-center transition-all relative"> 
            
            <div className="relative content-center mx-auto shadow-2xl shadow-indigo-900/40 h-64 w-64 mb-6 bg-gradient-to-r from-stone-100 to-stone-50 rounded-full p-6 ring-offset-0 ring-8 ring-stone-100/80">
                

                <PhoneIcon/>

                <Link href="https://voice.utopia.express" className="hover:text-stone-700" target="_blank">
                    <div className="absolute -left-6 bottom-9">
                        <h2 className="text-5xl font-extrabold">29<span className="text-sm">€/month</span></h2>
                        <Badge variant="voice" className="text-lg hover:bg-emerald-400">Call now!</Badge>   
                    </div>
                </Link>

            </div>   

          </div>       

        </div>

    </div>
  )
}




function UploadIcon() {
  return (
<svg className="w-10 h-10 stroke-stone-400 text-left" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor">
<path strokeLinecap="round" strokeLinejoin="round" d="M7.5 3.75H6A2.25 2.25 0 0 0 3.75 6v1.5M16.5 3.75H18A2.25 2.25 0 0 1 20.25 6v1.5m0 9V18A2.25 2.25 0 0 1 18 20.25h-1.5m-9 0H6A2.25 2.25 0 0 1 3.75 18v-1.5M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
</svg>

  )
}


function GenerateIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-10 h-10 stroke-stone-400 text-left">
<path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
</svg>


  )
}

function PhoneIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="mx-auto w-28 h-28 text-stone-800">
  <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 3.75v4.5m0-4.5h-4.5m4.5 0-6 6m3 12c-8.284 0-15-6.716-15-15V4.5A2.25 2.25 0 0 1 4.5 2.25h1.372c.516 0 .966.351 1.091.852l1.106 4.423c.11.44-.054.902-.417 1.173l-1.293.97a1.062 1.062 0 0 0-.38 1.21 12.035 12.035 0 0 0 7.143 7.143c.441.162.928-.004 1.21-.38l.97-1.293a1.125 1.125 0 0 1 1.173-.417l4.423 1.106c.5.125.852.575.852 1.091V19.5a2.25 2.25 0 0 1-2.25 2.25h-2.25Z" />
</svg>


  )
}


function ArrowIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="float-right ml-2 w-4 h-4">
  <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
  )
}


function GptIcon() {
  return (
    <svg className="w-4 h-4 float-left mr-2" viewBox='0 0 320 320' xmlns='http://www.w3.org/2000/svg'>
<path className="text-emerald-600" d='m297.06 130.97c7.26-21.79 4.76-45.66-6.85-65.48-17.46-30.4-52.56-46.04-86.84-38.68-15.25-17.18-37.16-26.95-60.13-26.81-35.04-.08-66.13 22.48-76.91 55.82-22.51 4.61-41.94 18.7-53.31 38.67-17.59 30.32-13.58 68.54 9.92 94.54-7.26 21.79-4.76 45.66 6.85 65.48 17.46 30.4 52.56 46.04 86.84 38.68 15.24 17.18 37.16 26.95 60.13 26.8 35.06.09 66.16-22.49 76.94-55.86 22.51-4.61 41.94-18.7 53.31-38.67 17.57-30.32 13.55-68.51-9.94-94.51zm-120.28 168.11c-14.03.02-27.62-4.89-38.39-13.88.49-.26 1.34-.73 1.89-1.07l63.72-36.8c3.26-1.85 5.26-5.32 5.24-9.07v-89.83l26.93 15.55c.29.14.48.42.52.74v74.39c-.04 33.08-26.83 59.9-59.91 59.97zm-128.84-55.03c-7.03-12.14-9.56-26.37-7.15-40.18.47.28 1.3.79 1.89 1.13l63.72 36.8c3.23 1.89 7.23 1.89 10.47 0l77.79-44.92v31.1c.02.32-.13.63-.38.83l-64.41 37.19c-28.69 16.52-65.33 6.7-81.92-21.95zm-16.77-139.09c7-12.16 18.05-21.46 31.21-26.29 0 .55-.03 1.52-.03 2.2v73.61c-.02 3.74 1.98 7.21 5.23 9.06l77.79 44.91-26.93 15.55c-.27.18-.61.21-.91.08l-64.42-37.22c-28.63-16.58-38.45-53.21-21.95-81.89zm221.26 51.49-77.79-44.92 26.93-15.54c.27-.18.61-.21.91-.08l64.42 37.19c28.68 16.57 38.51 53.26 21.94 81.94-7.01 12.14-18.05 21.44-31.2 26.28v-75.81c.03-3.74-1.96-7.2-5.2-9.06zm26.8-40.34c-.47-.29-1.3-.79-1.89-1.13l-63.72-36.8c-3.23-1.89-7.23-1.89-10.47 0l-77.79 44.92v-31.1c-.02-.32.13-.63.38-.83l64.41-37.16c28.69-16.55 65.37-6.7 81.91 22 6.99 12.12 9.52 26.31 7.15 40.1zm-168.51 55.43-26.94-15.55c-.29-.14-.48-.42-.52-.74v-74.39c.02-33.12 26.89-59.96 60.01-59.94 14.01 0 27.57 4.92 38.34 13.88-.49.26-1.33.73-1.89 1.07l-63.72 36.8c-3.26 1.85-5.26 5.31-5.24 9.06l-.04 89.79zm14.63-31.54 34.65-20.01 34.65 20v40.01l-34.65 20-34.65-20z'/>
</svg>
  )
}



