/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3E3dlWMavIx
 */
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { badgeVariants } from "@/components/ui/badge";
import Image from "next/image";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { Separator } from "@/components/ui/separator";



export function Youtube() {
  return (

    <div className="pb-9">
        <div className="py-9">
            <Link href="https://www.youtube.com/@theutopiaexpress" className="" target="_blank">
                    <p className="text-[10px] uppercase tracking-wider text-stone-400 hover:text-stone-800">
                        <span className="invisible md:visible">Utopia Express on Youtube</span>
                        <span className="float-right">youtube.com/@theutopiaexpress <ArrowIcon/></span>
                    </p>
            </Link>
            <Separator className="w-full h-px bg-stone-500/10 mt-4 mb-4"/>
        </div>

      <h1 className="py-12 animate-fade bg-gradient-to-br from-stone-900 to-stone-500 bg-clip-text text-center  font-extrabold tracking-tighter text-transparent drop-shadow-sm [text-wrap:balance] text-5xl md:text-7xl md:leading-[4rem]">Recharge & Relax</h1>
      <p className="animate-fade-up animate-delay-300 tracking-wide md:w-5/6 mx-auto text-2xl text-stone-500 dark:text-gray-100 transparent text-center">Uplifting Music by Utopia Express</p>

     
      
      <div className="md:w-2/3 mx-auto py-6 grid md:grid-cols-6 items-center gap-6 md:gap-8">
            
            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
              <Link target="_blank" href="https://www.youtube.com/watch?v=mWCDcuf-duU">
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/hbd.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
              </Link>
            </Card>
            

            
            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
              <Link target="_blank" href="https://www.youtube.com/watch?v=RdtWOAdNK6c">
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/future.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
              </Link>
            </Card>
            

            
            <Card className="mt-1 hover:mt-0 transition-all border-0 md:col-span-2 rounded-3xl shadow-xl hover:shadow-lg hover:shadow-slate-800/40 shadow-slate-800/40">
              <Link target="_blank" href="https://www.youtube.com/watch?v=EQPIQGrBb5k">   
                  <Image
                    alt="Image"
                    className="rounded-2xl transition-all cover saturate-100  shadow-lg"
                    src="/endless.jpg"
                    width= "1920"
                    height= "1080"
                    style={{
                      objectFit: "cover",
                    }}
                  />
              </Link>
            </Card>
            
      </div>

      <div className="md:w-2/3 mt-6 mx-auto grid grid-cols-2 h-14">

            <div>
              <audio controls src="/endless.mp3" className="mx-auto  scale-80"></audio>
            </div>
            
            <div>
              <Link target="_blank" href="https://4me3su0pmsb.typeform.com/to/D1vEjwko">
                <Button variant="outline" className=" text-slate-500 hover:text-slate-800 h-14 ">
                    <span className="ml-4">
                      Utopia Express on Youtube
                      </span>
                    <span className="float-right ml-2">
                    <Button variant="ghost" size="sm">
                      <ArrowIcon/>
                    </Button>
                    </span>
                </Button>
              </Link>
            </div>
       
      </div>



    </div>
  )
}

function ArrowIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="float-right ml-2 w-4 h-4">
  <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
</svg>
  )
}


function YoutubeIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 float-right" viewBox="0 0 28.57  20" focusable="false">
  <svg viewBox="0 0 28.57 20" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">
    <g>
      <path d="M27.9727 3.12324C27.6435 1.89323 26.6768 0.926623 25.4468 0.597366C23.2197 2.24288e-07 14.285 0 14.285 0C14.285 0 5.35042 2.24288e-07 3.12323 0.597366C1.89323 0.926623 0.926623 1.89323 0.597366 3.12324C2.24288e-07 5.35042 0 10 0 10C0 10 2.24288e-07 14.6496 0.597366 16.8768C0.926623 18.1068 1.89323 19.0734 3.12323 19.4026C5.35042 20 14.285 20 14.285 20C14.285 20 23.2197 20 25.4468 19.4026C26.6768 19.0734 27.6435 18.1068 27.9727 16.8768C28.5701 14.6496 28.5701 10 28.5701 10C28.5701 10 28.5677 5.35042 27.9727 3.12324Z" fill="#FF0000"></path>
      <path d="M11.4253 14.2854L18.8477 10.0004L11.4253 5.71533V14.2854Z" fill="white"></path>
    </g>
  </svg>
</svg>
  )
}



function ArrowLeftIcon() {
  return (
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-24 h-24 text-slate-300">
  <path strokeLinecap="round" strokeLinejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
</svg>


  )
}
function EurIcon() {
  return (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="w-4 h-4">
    <path strokeLinecap="round" strokeLinejoin="round" d="M14.25 7.756a4.5 4.5 0 1 0 0 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  )
}

function EmailIcon() {
    return (
<svg className="float-start w-4 h-4  mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
  <path className="stroke-stone-500" strokeLinecap="round" strokeLinejoin="round" d="M16.5 12a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0Zm0 0c0 1.657 1.007 3 2.25 3S21 13.657 21 12a9 9 0 1 0-2.636 6.364M16.5 12V8.25" />
</svg>
    )
}


function LearnIcon() {
    return (
<svg className="float-start w-4 h-4 mr-1" width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.75432 1.81954C7.59742 1.72682 7.4025 1.72682 7.24559 1.81954L1.74559 5.06954C1.59336 5.15949 1.49996 5.32317 1.49996 5.5C1.49996 5.67683 1.59336 5.84051 1.74559 5.93046L7.24559 9.18046C7.4025 9.27318 7.59742 9.27318 7.75432 9.18046L13.2543 5.93046C13.4066 5.84051 13.5 5.67683 13.5 5.5C13.5 5.32317 13.4066 5.15949 13.2543 5.06954L7.75432 1.81954ZM7.49996 8.16923L2.9828 5.5L7.49996 2.83077L12.0171 5.5L7.49996 8.16923ZM2.25432 8.31954C2.01658 8.17906 1.70998 8.2579 1.56949 8.49564C1.42901 8.73337 1.50785 9.03998 1.74559 9.18046L7.24559 12.4305C7.4025 12.5232 7.59742 12.5232 7.75432 12.4305L13.2543 9.18046C13.4921 9.03998 13.5709 8.73337 13.4304 8.49564C13.2899 8.2579 12.9833 8.17906 12.7456 8.31954L7.49996 11.4192L2.25432 8.31954Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>

    )
}





